# Generated by Django 6.0.1 on 2026-01-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.ImageField(upload_to='')),
                ('nombre_negocio', models.CharField(max_length=50)),
                ('slogan_1', models.CharField(blank=True, max_length=100)),
                ('slogan_2', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
