# Generated by Django 6.0.1 on 2026-01-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='icono',
            field=models.ImageField(upload_to='icono/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='slogan_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turismo',
            name='imagen',
            field=models.ImageField(upload_to='lugares/'),
        ),
    ]
