# Generated by Django 6.0.1 on 2026-01-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_info_icono_alter_info_slogan_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='icono',
            field=models.ImageField(upload_to='img/icono/'),
        ),
        migrations.AlterField(
            model_name='turismo',
            name='imagen',
            field=models.ImageField(upload_to='img/lugares/'),
        ),
    ]
